### ISSUE TITLE
CSS não está sendo implementado nas paginas do HTML

### ISSUE THREAD

**Issue by lua-mf** [majupeixoto/Space4Events#16]
A página base.html não está conseguindo encontrar a pasta do css

**Comment by aguiarth** [comment]
falta redirecionar o link pra pasta correta, corrigir a linha 14 do `base.html` para redirecionar para a pasta `static`

**Comment by aguiarth** [comment]
resolvido, era só corrigir a linha de redirecionamento mesmo e renomear a pasta onde estava o CSS:

Ajuste feito no `base.html`:
<link rel="stylesheet" href="{% static 'css/main.css' %}">

Além disso, como já comentado, o arquivo CSS estava vazio, realmente não iria aparecer nada... deixei um esqueleto base, precisamos elaborar
