### ISSUE TITLE
Url da Azure não funciona

### ISSUE THREAD

**Issue by majupeixoto** [majupeixoto/Space4Events#21]
![imagem_2024-04-07_134951045](https://github.com/majupeixoto/Space4Events/assets/143026488/b3a07c27-31c2-4972-b33d-c8691b2ed7ee)

**Comment by aguiarth** [comment]
qual a nossa URL?

**Comment by aguiarth** [comment]
resolvido em sala - link - https://space4events.azurewebsites.net/
