### ISSUE TITLE
Template login.html repete botão de login

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#22]
Porque o template `login.html` importa o `base.html`, as opções de login ficam repetidas, mas só o que funciona/importa é o do meio da página:

<img width="587" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/8e9b1418-b812-436f-836d-9f2093afc893">

Precisamos remover o botão da navbar, que inclusive fica maior do que o template `base.html`

**Comment by lua-mf** [comment]
adicionei uma condição no botão de login para que só apareça quando não estiver na página de login, agora se estiver na página de login não aprece mais o login em cima e se estiver na home o botão de login está bonitinho graças a Paulo que ajeitou o tamanho do botão!
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/5a9f706c-3366-4a6c-a256-bdf6b872ebc9)
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/e19f86fb-4935-43de-91bc-d8564d3e0fe3)
