### ISSUE TITLE
Filtro - a história está na navbar, mas seria melhor na home

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#29]
A história de filtrar espaços por cidade está como uma opção na navbar, mas seria melhor estar na home, que é onde aparecem todos os espaços:

<img width="593" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/6dea28f0-bca7-4576-b8f1-739f791edc64">

Não seria melhor uma barra de buscas em cima dos resultados, já na página inicial?

<img width="590" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/325760ec-0fc3-4074-aeec-28fa0ecdfae0">

**Comment by paulo-rago** [comment]
ajeitei
