### ISSUE TITLE
Pagamento reserva - NoReverseMatch

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#31]
Após preencher todos os campos e tentar efetuar uma reserva na página `pagamento_reserva`, me deparei com o seguinte erro:

<img width="544" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/d1d60c8f-5309-4fac-b0db-f8b98fbf3fce">

**Comment by lua-mf** [comment]
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/651a3491-f5ab-4a63-acd9-be628b430ce2)
após preencher todos os campos e efetuar uma reserva na página pagamento_reserva, fui direcionada a minhas reservas com os respectivas reservas e efetuei
