### ISSUE TITLE
Favoritos - nome do espaço não redireciona para detalhes

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#32]
Fiz login com o usuário "b" senha "123". Tenho 2 favoritos no momento, mas não consigo ver os detalhes dos espaços se eu quiser:

<img width="596" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/0f7c2a21-d0da-4365-83a8-9ebd757fa3a2">

Os nomes parecem um link em hover, mas não se comportam assim

**Comment by lua-mf** [comment]
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/dc0cf7a3-9ba5-4985-91fb-bfbc6a63fadf)
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/29fbd158-1e75-4e33-8506-6b3e347699bf)
entrei em meus favoritos e consigo visualizar agora e apertei em ver mais e consegui visualizar mais detalhes
