### ISSUE TITLE
Reservas - reserva efetuada não aparece em minhas_reservas

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#33]
No usuário "b", senha 123, tentei reservar o "apartamento luxo". Aparentemente concluí a reserva, mas ela não aparece em minhas_reservas:

<img width="590" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/013fbd17-43ab-4d90-af9b-88449a23c8f0">

**Comment by aguiarth** [comment]
no mesmo usuário logado, tentei reservar o espaço "chalé rústico", check-in 12.06.02024 e checkout 15.06.2024, 1 hóspede. Segui para a página `pagamento_reserva` sem problemas, digitei o número do cartão 1, validade 1, cvv 1 (estamos sem as validações no momento) e cliquei em pagar. A reserva não aparece em minhas reservas:

<img width="590" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/eab3ec04-bfda-4532-87dc-d891757c144e">

**Comment by lua-mf** [comment]
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/d27050d7-4dae-426d-aebb-210aec3ee3ae)
foi resolvido!!
