### ISSUE TITLE
reservas com check in depois de check out são aceitas

### ISSUE THREAD

**Issue by lua-mf** [majupeixoto/Space4Events#34]
![Imagem do WhatsApp de 2024-04-28 à(s) 18 00 31_3fd97c56](https://github.com/majupeixoto/Space4Events/assets/148653658/d7fed830-5b16-4695-a02a-2f5ac3bd900d)

**Comment by aguiarth** [comment]
corrigido com datetime: view compara as datas e exige check-in anterior
