### ISSUE TITLE
se não adicionar todas as informações para a reserva e apertar em confirmar mostra página de erro

### ISSUE THREAD

**Issue by lua-mf** [majupeixoto/Space4Events#38]
testei assim: 
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/c6c48b00-607c-4bef-8614-10bb1bec4ee0)
e apareceu essa página de erro: 
![Captura de tela_29-4-2024_8309_127 0 0 1](https://github.com/majupeixoto/Space4Events/assets/148653658/48524213-2589-4f27-8453-dd815c340536)

**Comment by aguiarth** [comment]
corrigido: agora todos os campos são obrigatórios e orientam o formato de entrada de dados esperado
