### ISSUE TITLE
Filtros - botão de busca sobrepõe campo de inserir data

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#44]
Na página inicial, a opção "buscar" aparece sobreposta ao campo de inserir data:

<img width="598" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/f98faa2a-2d19-4387-b11d-e1041f7e0396">

Além disso, o botão desaparece quando o usuário clica no campo de data:

<img width="596" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/9d7f5dda-ed6f-46c9-9df9-743d650cb340">

**Comment by lua-mf** [comment]
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/dcd09820-95d1-43d1-a157-750effcee8b5)
