### ISSUE TITLE
CSS - Navbar - no logout, há um ícone quase invisível

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#45]
A navbar da aplicação é preta e tem um ícone de saída bem escuro ao lado do nome "logout", quase não aparece (canto superior direito):

<img width="88" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/b35c187e-b0b3-4563-878f-4b57ef288dcb">

**Comment by lua-mf** [comment]
no login também está
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/ab6742b0-9279-4a2a-a80b-c8af6d10ced0)

**Comment by lua-mf** [comment]
exclui o icone de porta com uma seta que tinha no botão de login e de logout
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/6706ff86-786e-4f96-909e-20350a131ea0)
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/8ca3625a-798a-4bf7-a4b8-fbd82df1fb23)
