### ISSUE TITLE
depois de fazer reserva se eu tentar voltar dá erro na página

### ISSUE THREAD

**Issue by lua-mf** [majupeixoto/Space4Events#46]
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/80e7510b-d0ef-49d6-8ac6-14870be25fbc)
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/5d69dd36-00d8-4d01-a30c-541f34496f8f)

**Comment by paulo-rago** [comment]
resolvido em: 3ec07cea08c65324d2defd31f57cbcb88734348b
