### ISSUE TITLE
pagamento em débito não está funcionando-vai para página de erro!

### ISSUE THREAD

**Issue by lua-mf** [majupeixoto/Space4Events#52]
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/424268d3-c1a6-45bc-9c7d-402a8e57222a)
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/e3bdb791-382c-4b99-8d0b-06808ea20f3a)

**Comment by majupeixoto** [comment]
concluído com o commit eeb8f50 - agora, o pagamento é feito corretamente e não vai para a página de erro
