### ISSUE TITLE
Aplicação inteira - aplicação não é responsiva

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#57]
Esse precisa de atenção. Nossa aplicação não é responsiva para dispositivos móveis:

<img width="955" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/0c8983fd-53f1-4d56-91c6-5b89ccc57b56">

**Comment by aguiarth** [comment]
gente, isso aqui acho q era só a home como comentei em sala com @paulo-rago - resolvemos isso?

**Comment by paulo-rago** [comment]
resolvido em: 5046f31ae44082d914b69ea4dfe38af1794db0e3
