### ISSUE TITLE
Minhas reservas - aba não exibe mais espaços reservados

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#61]
Isso já funcionava antes, mas agora uma reserva efetuada não aparece mais em "minhas reservas":

<img width="770" alt="image" src="https://github.com/majupeixoto/Space4Events/assets/155742254/bbdc1929-4390-4b7a-988a-d0df14b342b8">

**Comment by lua-mf** [comment]
A reserva só realizada se o campo de nome do hóspede na reserva for igual ao nome do usuário no cadastro 
Assim não funciona, pois meu nome de usuário é lua:
![Imagem do WhatsApp de 2024-05-21 à(s) 20 31 42_aadae5e3](https://github.com/majupeixoto/Space4Events/assets/148653658/c734c924-afa3-49b9-b560-e53772362995)
![Imagem do WhatsApp de 2024-05-21 à(s) 20 32 09_bef44f81](https://github.com/majupeixoto/Space4Events/assets/148653658/620216f5-3218-44fc-9630-98b59759ca3b)
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/145c39d5-0fff-41fd-973b-fa8e3a409a22)
![Imagem do WhatsApp de 2024-05-21 à(s) 20 34 48_23fe11c1](https://github.com/majupeixoto/Space4Events/assets/148653658/3fbc9ff7-2534-423c-8a55-f08a66a09fa5)
