### ISSUE TITLE
CSS - alterar ícone dragão

### ISSUE THREAD

**Issue by aguiarth** [majupeixoto/Space4Events#64]
Tentei colocar uma casinha do favicon mas errei alguma coisa, @paulo-rago consegue ajudar a gente nisso?

O favicon:
`<i class="fa-duotone fa-house" style="--fa-primary-color: #63E6BE; --fa-secondary-color: #63E6BE;"></i>`

Deixei um comentário na linha 5 do `partials` > `menu.html`

**Comment by paulo-rago** [comment]
@aguiarth Esse ícone é do modelo pago do font-awsome, por isso não funciona :')
![image](https://github.com/majupeixoto/Space4Events/assets/149490954/d07cdfb6-0dcf-440d-a176-3b6cf1776979)
