### ISSUE TITLE
quando a perto pela primeira vez em 1 estrela e confirmo ele dá erro, mas se tentar de novo funciona

### ISSUE THREAD

**Issue by lua-mf** [majupeixoto/Space4Events#65]
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/165e6a61-8b62-44a6-8836-b33a9badad3c)

**Comment by paulo-rago** [comment]
problema resolvido em: 6237b73dbc0a2baf73ce1dcf47bb2efe2544c2ac
