### ISSUE TITLE
Consegue fazer cadastro de espaço sem imagem, o que não deveria ser permitido (tornar adicionar imagem como obrigatório em cadastro de espaço)

### ISSUE THREAD

**Issue by lua-mf** [majupeixoto/Space4Events#67]
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/bb6f48ab-4669-4554-b250-db446647a1ea)

**Comment by paulo-rago** [comment]
Lua, é pra ficar assim mesmo. Quem alterou isso fui eu pq durante os testes do cypress não tem como adicionar imagens.

**Comment by aguiarth** [comment]
Lua, esse era o objetivo, vamos fechar aqui
