### ISSUE TITLE
"Meus Espaços" não funciona na Azure

### ISSUE THREAD

**Issue by dekenner** [majupeixoto/Space4Events#70]
"Meus Espaços" não funciona na Azure. Dá um erro na tela.
![imagem_2024-05-20_082053832](https://github.com/majupeixoto/Space4Events/assets/149336406/5ab86ba0-3061-4d96-8ec7-c36b2c4731a3)

**Comment by paulo-rago** [comment]
no último deploy isso foi resolvido
