### ISSUE TITLE
O próprio proprietário do espaço pode reservar o seu espaço

### ISSUE THREAD

**Issue by lua-mf** [majupeixoto/Space4Events#73]
loguei com "lua", ao cadastrar espaço e ir em ver mais aparece a opção reservar espaço mesmo sendo a proprietária do espaço
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/8a0c9f00-b6e9-45b5-99cb-c7f67308085b)

**Comment by paulo-rago** [comment]
fechado em: ac07050e206a709017b83fd32e5496e8c39c4243
