### ISSUE TITLE
o botão de favoritos está diferente quando o usuário não está logado

### ISSUE THREAD

**Issue by lua-mf** [majupeixoto/Space4Events#74]
antes de logar aparecea ssim o botão de favoritar: 
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/1436adbf-3d0b-447c-b464-0c924ff4880c)
depois de logar que aprece como tem que ser :
![image](https://github.com/majupeixoto/Space4Events/assets/148653658/ea338054-972e-4186-89f9-01f499351ac0)

**Comment by paulo-rago** [comment]
resolvido em: 4396d53986a15c93d3102ea7bef172b4d8c67561
